### PR TITLE
Add copyPath and copyPathSync.

### PR DESCRIPTION
**Pull request by matanlurey**
Closes https://github.com/dart-lang/io/issues/7.

### CODE REVIEW

**Comment by kevmoo** [comment]
dev dependencies oops? See travis...

**Comment by matanlurey** [comment]
Thanks. PTAL @kevmoo

**Comment by matanlurey** [comment]
@kevmoo Thanks! Clarified, and caught the nested case and throw (+test).

**Comment by kevmoo** [comment]
Another push coming?

**Comment by matanlurey** [comment]
@kevmoo Yup. Sorry about that.

**Pull request merged**
