### PR TITLE
copyPath: add parameter followLinks

### PR DESCRIPTION
**Pull request by gmpassos**
`Directory.listSync` only returns `Link` entries if `followLinks: false` is passed. 

`copyPath` needs a `followLinks` parameter to configure the call of `Directory.listSync` and allow the copy of `Link` entries, as expected by line `else if (file is Link) {`

### CODE REVIEW

**Comment by natebosch** [comment]
Can you add a test and a CHANGELOG entry?

**Comment by gmpassos** [comment]
> Can you add a test and a CHANGELOG entry?

👍:
https://github.com/gmpassos/dart-io-copy-path-test

**Comment by natebosch** [comment]
Thanks for the example - can we find a way to test this in the local unit tests?

We also still need a CHANGELOG entry.

https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#changelog-entries

**Comment by gmpassos** [comment]
> Thanks for the example - can we find a way to test this in the local unit tests?
> 
> We also still need a CHANGELOG entry.

I will try this in the next week. Regards.

**Comment by gmpassos** [comment]
Still need an unit test?

**Comment by natebosch** [comment]
> Still need an unit test?

Yes - if we break this functionality there should be some local test which signals the problem.

**Comment by mosuem** [comment]
Closing as the [dart-lang/io](https://github.com/dart-lang/io) repository is merged into the [dart-lang/tools](https://github.com/dart-lang/tools) monorepo. Please re-open this PR there!

**Comment by gmpassos** [comment]
Re-opened at:

https://github.com/dart-lang/tools/pull/1267

**Pull request closed without merging**
